version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
